#!/bin/bash
chromosomes=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X Y M)

input_hic_file="/work/aligned/inter_30.hic"
output_dir="/work/oeinteractions"
juicer_tools_jar="/HIC/juicer/CPU/common/juicer_tools.jar"

mkdir -p $output_dir

for chr in "${chromosomes[@]}"; do
output_file="${output_dir}/chr${chr}_whole_matrix.txt"
echo "Processing chromosome ${chr}..."
java -jar $juicer_tools_jar dump oe NONE $input_hic_file chr${chr} chr${chr} BP 25000 $output_file
echo "Output saved to ${output_file}"
done

echo "All chromosomes processed."
